### ISSUE TITLE
Error messages not always propagated from F* to Emacs

### ISSUE THREAD

**Issue by beurdouche** [FStarLang/fstar-mode.el#21]
Hey ! =)

It seems that some error messages are not propagated from F\* to emacs in interactive mode using a build-config.
- If there is no build-config, errors get printed in emacs. This is ok.
  ![screen shot 2015-09-22 at 21 43 16](https://cloud.githubusercontent.com/assets/1193431/10029740/f02b0596-6173-11e5-8838-273d8f6280a6.jpg)
- If there is a correct build-config, no problem either. This is ok.
  ![screen shot 2015-09-22 at 21 44 55](https://cloud.githubusercontent.com/assets/1193431/10029907/02c1345e-6175-11e5-81b7-21f663a58ba0.jpg)
- If there is an incorrect build-config and the type-checking fails, F\* returns an error message, but it does not appear in Emacs.
  (The text is briefly highlighted as usual and of course doesn't stay violet as it failed to verify the block but no error message...)
  ![screen shot 2015-09-22 at 21 46 22](https://cloud.githubusercontent.com/assets/1193431/10029898/ee77d20a-6174-11e5-82d3-50bb06a1bb46.jpg)

**Comment by beurdouche** [comment]
By the way, maybe always having a feedback would be nice ?
Printing "OK" or "Success" in emacs when everything goes fine
Printing "ERROR : blabla" in emacs on failure

**Comment by cpitclaudel** [comment]
Thanks for that feedback! I'll look at it now.

**Comment by cpitclaudel** [comment]
Ok, I see where the problem is from: this is another case of F*'s error messages not being consistent:

```
Error: Could not parse a valid build configuration from ; Invalid options : unrecognized option '--admit-fsi'
```

**Comment by cpitclaudel** [comment]
Ah, I see the actual issue here. The problem is that the F* subprocess exits after that error, but before printing the `#done` flag, so the Emacs mode never knows that the message is complete. I'm not sure what I can do about this particular issue; it would seem better for the interactive mode to print one last `#done` before exiting :/

**Comment by cpitclaudel** [comment]
I looked at the code in a bit more detail, and I think this should be too hard to fix on the F* side.  The problem is that F* exits right after starting with an error message if it can't parse the current document.  fstar-mode doesn't know why it exited, and doesn't know what to do with that output.

I can fix it partially on the Emacs side by displaying the remaining output, but it won't be very nice. 

Instead, the F* side could be changed to delay looking for dependencies (that's the part that causes a parse) until it receives a "#init" query, or something like this.  Then if the parsing failed F* would print the error (as it does now), print a `#done-nok`, and exit.  F*-mode would process the error message just fine, because it would come in response to an IDE query ("#init").

I think that should be a pretty simple patch (all in `FStar.Interactive.fs`).

**Comment by cpitclaudel** [comment]
Fixing this would be nice: there are [tutorial entries](https://github.com/FStarLang/FStar/wiki/Early-stumbling-blocks,-FAQ) and [README tips](https://github.com/mitls/mitls-fstar#configuring-emacs-mode) about this bug.
